//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBook.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaBibliotecaPerfilesEntities : DbContext
    {
        public SistemaBibliotecaPerfilesEntities()
            : base("name=SistemaBibliotecaPerfilesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_modulo> tb_modulo { get; set; }
        public virtual DbSet<tb_operaciones> tb_operaciones { get; set; }
        public virtual DbSet<tb_rol> tb_rol { get; set; }
        public virtual DbSet<tb_rol_operacion> tb_rol_operacion { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
    }
}
