//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBook.Entity
{
    using System;
    using System.Collections.Generic;
    public partial class tb_libros
    {
        public int idLibro { get; set; }
        public string tituLibro { get; set; }
        public string nomAutor { get; set; }
        public string sinopsis { get; set; }
        public Nullable<decimal> precUni { get; set; }
        public Nullable<System.DateTime> fechPub { get; set; }
        public Nullable<int> idEdito { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> idcate { get; set; }
    
        public virtual tb_editoriales tb_editoriales { get; set; }
    }
}
