//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBook.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rol_operacion
    {
        public int id { get; set; }
        public int idRol { get; set; }
        public int idOperacion { get; set; }
    
        public virtual tb_operaciones tb_operaciones { get; set; }
        public virtual tb_rol tb_rol { get; set; }
    }
}
